# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = "301 redirect handler using Fastly KV Store"
language = "javascript"
manifest_version = 3
name = "redirect-handler"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.origin_0]
      override_host = "example.com"
      url = "https://example.com"

  [local_server.kv_stores]

    [local_server.kv_stores.redirects_store]
      file = "local-redirects.json"
      format = "json"

[setup]

  [setup.backends]

    [setup.backends.origin_0]
      address = "example.com"
      port = 443
